### ISSUE TITLE
Can we still use Blackfire ?

### ISSUE THREAD

**Issue by heyyo-droid** [wodby/php#178]
I saw that Blackfire support was removed from wodby in recent wody/php versions.
Is there still a way to use it ?

Why this third party was removed ?

**Comment by csandanov** [comment]
the extension was removed because blackfire no longer has a free subscription which was the only reason we added it in the first place and also makes it less appealing for me to debug blackfire-related issues, you can build your own image and install the extension or you can use an open-source alternative (webgrind, xhprof) or other solutions that have a free subscription like newrelic apm

**Comment by heyyo-droid** [comment]
Thanks I got you, makes sense.
I didn't know newrelic had a free subscription, maybe I will give it a try.

**Comment by heyyo-droid** [comment]
@csandanov 

1 year later, we are missing Blackfire ...

We tried to replace Blackfire, with New Relic free edition, and webgrind, xhprof. 
It's really not as good as Blackfire to debug Drupal performance.

We also tried to add build our own image from wodby/php it means we are missing all your work and updates in wodby/drupal-php

It's true, there isn't free version anymore, but the cost of it worth it. 
Even in Drupal development, people are ready to pay for other stuff like PhpStorm vs Visual Studio Code.

Now we wanted to test the speed improvement by using PHP Opcache preloading, the last wodby/php image supporting blackfire is a PHP 8.1 one. But the project generating preload.php for Drupal 10 requires only PHP 8.2...

Blackfire is really easy to use, and optimized for detecting performances issues in Drupal.

May you reconsider the inclusion in your php image ?
